title: Salah al-Din at-Thani Taymullah
url: "https://DeenAthani.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/DeenAthani"
footer_text: "© 2026 Salah al-Din Taymullah"

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Research"
    link: "research"
  - name: "Publications"
    link: "publications"
  - name: "Resume"
    link: "resume.pdf"
  - name: "Blog"
    link: "https://deenathani.hashnode.dev"
  - name: "Contact"
    link: "contact"
