title: Al-Thani
url: "https://DeenAthani.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

description: "Researcher building neural machine translation systems. B.S. Computer Science, WGU."
author: "Salah al-Din T."

tracking_id: #

footer: yes
footer_url: "https://github.com/DeenAthani"
footer_text: "© 2026 Salah al-Din T."

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Research"
    link: "research"
  - name: "Publications"
    link: "publications"
  - name: "Blog"
    link: "https://deenathani.hashnode.dev"
  - name: "Contact"
    link: "contact"
